#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

// auto-generate necessary directories

foreach (['database', 'log'] as $dir) {
    $path = __DIR__ . '/' . $dir;

    if (file_exists($path) && is_dir($path)) {
        continue;
    }

    mkdir($path);
}

// execute commands

$command = @$argv[1];

if (!$command || $command === 'server') {
    shell_exec('/usr/bin/php -S localhost:8085 index.php');
}

if ($command === 'migrate') {
    shell_exec('/usr/bin/php migrate.php');
}

if ($command === 'play') {
    require __DIR__ . '/playground.php';
}

if ($command === 'trash') {
    $table = @$argv[2];

    if(! $table) {
        die('Please enter table' . PHP_EOL);
    }

    $trashed = \App\Lib\DB::init()->trashedOnly($table);

    foreach($trashed as $record) {
        echo json_encode(array_values($record)), PHP_EOL;
    }
}

if($command === 'restore') {
    $table = @$argv[2];

    if(! $table) {
        die('Please enter table' . PHP_EOL);
    }

    $id = @$argv[3];

    if(! $id) {
        die('Please enter an id' . PHP_EOL);
    }

    \App\Lib\DB::init()->restore($table, (int) $id);

    echo "Restored $table with id $id.", PHP_EOL;
}
