#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

// auto-generate necessary directories

foreach (['database', 'log'] as $dir) {
    $path = __DIR__ . '/' . $dir;

    if (file_exists($path) && is_dir($path)) {
        continue;
    }

    mkdir($path);
}

// execute commands

$command = @$argv[1];

if (!$command || $command === 'server') {
    shell_exec('/usr/bin/php -S localhost:8085 index.php');
}

if ($command === 'migrate') {
    shell_exec('/usr/bin/php migrate.php');
}

if ($command === 'play') {
    require __DIR__ . '/playground.php';
}
